# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f959e9a7627507274c1746d08df481faf2f3ea747d47574c86ae40c8ccc3e0d613a3eeeed5fc67842e0b82e14b699b057f934fcd0b02918166cf389ed501075f

test:
  secret_key_base: 9c120dd506d0ffd6d41ca3795245bf981e950e6a2bb9f5fdbaf95066189511db8fa9b091fd04dcc43cffa3fdac4009ec961a08d7a6e35a22467386eac20083b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
